name: tynewsauto
region: sgp
services:
  - name: web
    dockerfile_path: Dockerfile
    github:
      repo: kkhwan1/newstown
      branch: main
      deploy_on_push: true
    http_port: 8080
    instance_size_slug: professional-s
    instance_count: 1
    routes:
      - path: /
    health_check:
      http_path: /health
      initial_delay_seconds: 30
      period_seconds: 30
    envs:
      - key: API_PORT
        value: "8080"
      - key: DEBUG
        value: "false"
      - key: JWT_SECRET_KEY
        type: SECRET
      - key: GOOGLE_SHEET_URL
        type: SECRET
      - key: GOLFTIMES_ID
        type: SECRET
      - key: GOLFTIMES_PW
        type: SECRET
      - key: NAVER_CLIENT_ID
        type: SECRET
      - key: NAVER_CLIENT_SECRET
        type: SECRET
      - key: GOOGLE_CREDENTIALS_BASE64
        type: SECRET
      - key: CORS_ORIGINS
        value: ""
